movieproj/movieapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views
app_name = 'movieapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.addmovie,name='addmovie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproj/movieproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

movieproj/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=200)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

movieproj/movieapp/forms.py
from .models import Movie
from django import forms

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','desc','year','img']

movieproj/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movie = Movie.objects.all()
    return render(request,'index.html',{'movie':movie})

def detail(request,movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request,'detail.html', {'movie': movie})

def addmovie(request):
    if request.method == 'POST':
        name = request.POST.get('moviename',)
        year = request.POST.get('year',)
        desc = request.POST.get('desc',)
        img = request.FILES['img']
        user = Movie(name=name,year=year,desc=desc,img=img)
        user.save();
    return render(request,'add.html')

def update(request,id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})


def delete(request,id):
    if request.method == "POST":
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproj/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
    <input type="text" name="moviename" placeholder="Movie Name"><br>
    <input type="text" name="year" placeholder="Release Year"><br>
    <input type="text" name="desc" placeholder="Description"><br>
    <h1></h1>
    <input type="file" name="img"><br>
    <div> <h1></h1> </div>
    <input type='submit'>


</form>
{% endblock %}

movieproj/templates/base.html
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Movie Mania</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
        &nbsp;&nbsp;MovieSpace
  </a>
</nav>
<br>
<br>
{% block body %}
{% endblock %}
</body>
</html>

movieproj/templates/delete.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  Are you sure you want to delete this file???
  <input type="submit">
</form>

movieproj/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" alt="" width="300" height="330" style="margin:7px;">
        </div>
        <div class="col-md-6">
            <h2>{{movie.name}}</h2>
            <h3>Year : {{movie.year}}</h3>
            <p>{{movie.desc}}</p>
            <a class="btn btn-primary" href="{% url 'movieapp:update' movie.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>




    </div>
</div>

{% endblock %}

movieproj/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

movieproj/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="contaier">
    <div class="row">
        {% for i in movie %}<br>
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100" height="350">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
<!--    <p class="card-text">{{i.desc}}</p>-->
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">Know More</a>
  </div>
</div>
        </div>
        {% endfor %}

    </div>
</div>
<!--<a href="{% url 'movieapp:addmovie' %}" class="btn btn-dark">Add</a>-->
{% endblock %}